name: CI

on:
  pull_request:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    name: PHP ${{ matrix.php }} PHPTS ${{ matrix.phpts }} OPcache ${{ matrix.opcache }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
        phpts: ["ts", "nts"]
        opcache: [1, 0]

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: opcache.enable_cli=${{ matrix.opcache }}
        env:
          phpts: ${{ matrix.phpts }}

      - name: Install extension
        working-directory: ${{ github.workspace }}
        run: |
          phpize
          ./configure --with-php-config=/usr/bin/php-config
          sudo make -j8 install

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v3"
        with:
          composer-options: "--prefer-dist"

      - name: Run PHPUnit tests
        run: composer test
